version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:SnO2WMaN-HQ/bookshelf-nest-api.git
analyze:
  modules:
    - name: .
      type: npm
      target: .
      path: .
